#!/usr/bin/env python
import os
import subprocess
import taglib

# Globals
delimeter = "\t" # " - "

# Functions
def convert_seconds(sec):
    minutes = int(sec / 60)
    secs = sec % 60

    if secs == 0:
        secs = "00"

    return  str(minutes) + ":" + str(secs)

# unused
# leaving this here for now
# sadly lacks utf8
def mp3info_line(file):
    result = subprocess.run(["mp3info", '-p %n - %t - %m:%s', file], stdout=subprocess.PIPE)
    print(result.stdout)
    return result.stdout.decode("utf-8")

def taglib_line(file):
    song = taglib.File(file)
    tags = song.tags
    return tags["TRACKNUMBER"][0].split("/")[0] + delimeter + tags["TITLE"][0] + delimeter + convert_seconds(song.length)

# Script
track_to_num = lambda t: str(t).split(delimeter)[0]
files = os.listdir(os.getcwd())
tracks = []

for file in files:
    if str(file).find(".mp3") is not -1:
        tracks.append(taglib_line(file))


tracks.sort(key=track_to_num)


for track in tracks:
    print(track)


