#!/usr/bin/env python3
"""checks if a the wpa_supplicant is running"""
import sys
import ini
import wpa_status

config = ini.parse(open("/etc/wpa_statusd.ini").read())
client = wpa_status.Client(config["socket"])
running_resp = wpa_status.is_supplicant_running(client)
running = running_resp.result["SupplicantRunning"]["running"]

if running:
    sys.exit(0)

sys.exit(1)
